# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'tool/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'tool/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: tool/oreilly_data_createor/package-lock.json
    - run: npm ci
      working-directory: ./tool/oreilly_data_createor
    - run: npm run build
      working-directory: ./tool/oreilly_data_createor
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: tool/oreilly_data_createor/files
           destination_dir: sample-data
           force_orphan: true
           
